checkout latest all and add one line of css to copy box
teambit/documenter pull request #18
Opened 2021-05-27 17:13 UTC by JoshK2

2021-05-27 17:24 UTC, odedre commented
you're not up to date with master

2021-05-27 17:25 UTC, odedre requested changes

2021-05-27 17:25 UTC, odedre commented on .bitmap
> +        "version": "3.0.13",
please pull master

2021-05-30 19:05 UTC, JoshK2 commented on .bitmap
> +        "version": "3.0.13",
done

2021-05-30 19:35 UTC, merged